### ISSUE TITLE
Add PYPI_PASSWORD GitHub Secret with PyPI upload API token

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKMGHImageIO#28]
To enable automated package updates on release as documented:

https://itkpythonpackage.readthedocs.io/en/master/Build_ITK_Module_Python_packages.html#automate-pypi-package-uploads

@jcfr I do not have permissions to do this on the repository -- could you please add it?

**Comment by jcfr** [comment]
> I do not have permissions to do this on the repository -- could you please add it?

I just added you to https://github.com/orgs/Slicer/teams/slicer-admin/members, this should allow you to update the settings.

**Comment by thewtex** [comment]
Thanks @jcfr ! Token added.
