### ISSUE TITLE
MGHIO File Writing is incorrect

### ISSUE THREAD

**Issue by hjmjohnson** [InsightSoftwareConsortium/ITKMGHImageIO#7]
The MGHIO file writing seems to have bugs when certain direction cosigns are used.  There seems to be a bug in computing the correct origin to store in the .mgz file

TODO: 
1) use freesurfer's mriconvert to read a reference.nii.gz file and write a proper reference.mgh file
2) write a test case that reads the nii.gz file, and writes a temporay test.mgh file
3) compare the test.mgh file to the reference.mgh file
4) read the reference.mgh file and compare to the reference.nii.gz file

HINTS:

Refactor the code to replace c-style arrays with itk::Vector and itk::Matrix, then use matrix operations to describe the mathemetics that need to occur.

For example when converting from RAS to LPS, multiply by a matrix:
LPS2RPS=
[  -1  0  0;
   0  -1  0;
   0  0   1]

https://surfer.nmr.mgh.harvard.edu/fswiki/CoordinateSystems?action=AttachFile&do=get&target=fscoordinates.pdf

itk::Point      (  .GetVectorFromOrigin() )
itk::Vector
itk::Matrix

**Comment by hjmjohnson** [comment]
Fixed!

**Comment by jcfr** [comment]
:8ball:
